name: Handle stale issues and PRs

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # Issues config
          days-before-issue-stale: 60
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          days-before-issue-close: 7
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          # PRs config
          days-before-pr-stale: 45
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          days-before-pr-close: 10
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
